AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AmplifyApp:
    Type: "AWS::Amplify::App"
    Properties: 
      Name: "MyNextJsApp"
      Repository: "https://github.com/saurabhpanth26/next-js-application.git"
      OauthToken: "{{resolve:ssm:/github/token}}"
      BuildSpec: "amplify.yml"

  AmplifyBranch:
    Type: "AWS::Amplify::Branch"
    Properties: 
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: "main"
      EnableAutoBuild: true
      Stage: "PRODUCTION"

Outputs:
  AmplifyAppURL:
    Description: "URL of the deployed Next.js application"
    Value: !Sub "https://${AmplifyBranch.BranchName}.${AmplifyApp.DefaultDomain}"
